# Generated by Django 6.0.5 on 2026-05-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='请求路径')),
                ('query_string', models.CharField(blank=True, default='', max_length=500, verbose_name='查询参数')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='状态码')),
                ('duration_ms', models.FloatField(verbose_name='耗时(ms)')),
                ('user', models.CharField(blank=True, default='anonymous', max_length=150, verbose_name='用户')),
                ('ip', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='请求体')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='响应体')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': '请求日志',
                'verbose_name_plural': '请求日志',
                'db_table': 'request_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
