# Generated by Django 6.0.5 on 2026-09-17 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_workflownoderun_workflow_and_more'),
        ('projects', '0005_conversation_tool_approval_required'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=128)),
                ('arguments', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('denied', 'denied'), ('expired', 'expired'), ('cancelled', 'cancelled')], db_index=True, default='pending', max_length=16)),
                ('decision', models.CharField(blank=True, default='', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='projects.conversation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='agents.agentrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tool_executions',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
