# Generated by Django 6.0.5 on 2026-09-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_workflownoderun_workflow_and_more'),
        ('projects', '0005_conversation_tool_approval_required'),
        ('tools', '0002_toolexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceWrite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=512)),
                ('previous', models.TextField(blank=True, null=True)),
                ('proposed', models.TextField()),
                ('status', models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('rolled_back', 'rolled_back')], db_index=True, default='applied', max_length=16)),
                ('applied', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_writes', to='projects.conversation')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_writes', to='agents.agentrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_writes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_writes',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
