# Generated by Django 6.0.5 on 2026-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=64)),
                ('api_key_encrypted', models.CharField(max_length=512)),
                ('base_url', models.CharField(default='https://api.openai.com/v1', max_length=256)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=128)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_configs',
            },
        ),
    ]
