# Generated by Django 6.0.5 on 2026-06-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0002_initial'),
        ('bids', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('fast', '快速生成'), ('hermes', 'Hermes 深度生成')], default='fast', max_length=16)),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '生成中'), ('done', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=16)),
                ('prompt', models.TextField(blank=True, default='')),
                ('context', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='bids.bidchapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '生成任务',
                'verbose_name_plural': '生成任务',
                'db_table': 'generation_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
