# Generated by Django 6.0.5 on 2026-07-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0003_generationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
