# Generated by Django 6.0.5 on 2026-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_config', '0004_generationtask_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerationTask',
        ),
    ]
