# Generated by Django 6.0.5 on 2026-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('deck', 'Deck'), ('report', 'Report')], default='chat', max_length=32),
        ),
    ]
