# Generated by Django 6.0.5 on 2026-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_conversation_cancel_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tool_approval_required',
            field=models.BooleanField(default=False),
        ),
    ]
