# Generated by Django 6.0.5 on 2026-05-19 00:10

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.files.models.upload_to, verbose_name='文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('doc', 'Word 97-2003'), ('txt', '文本'), ('other', '其他')], default='other', max_length=10, verbose_name='文件类型')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
