# Generated by Django 6.0.5 on 2026-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('md', 'Markdown'), ('docx', 'Word'), ('doc', 'Word 97-2003'), ('txt', '文本'), ('other', '其他')], default='other', max_length=10, verbose_name='文件类型'),
        ),
    ]
