# Generated by Django 6.0.5 on 2026-07-02 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('slug', models.CharField(max_length=64, unique=True, verbose_name='slug')),
                ('skill', models.CharField(default='bid-writing/bid-chapter-writer', help_text='hermes_skills 下的技能路径(不含后缀), 如 bid-writing/bid-chapter-writer', max_length=128, verbose_name='技能')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='额外注入 system prompt 的内容(叠加在技能之上)')),
                ('default_max_steps', models.IntegerField(default=8, verbose_name='默认最大步数')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='用户任务')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('done', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('answer', models.TextField(blank=True, default='', verbose_name='最终答案')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('step_count', models.IntegerField(default=0, verbose_name='步数')),
                ('max_steps', models.IntegerField(default=8, verbose_name='最大步数')),
                ('tools_used', models.JSONField(blank=True, default=list, verbose_name='用过的工具')),
                ('session_id', models.CharField(blank=True, default='', help_text='Hermes 跨会话记忆 key', max_length=64, verbose_name='会话ID')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agents.agent', verbose_name='Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent执行',
                'verbose_name_plural': 'Agent执行',
                'db_table': 'agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('type', models.CharField(choices=[('plan', '规划'), ('tool_call', '工具调用'), ('tool_result', '工具结果'), ('answer', '最终答案'), ('error', '错误')], max_length=16, verbose_name='类型')),
                ('status', models.CharField(choices=[('ok', '成功'), ('error', '失败'), ('skipped', '跳过')], default='ok', max_length=16)),
                ('thought', models.TextField(blank=True, default='', verbose_name='思考')),
                ('tool_name', models.CharField(blank=True, default='', max_length=64, verbose_name='工具名')),
                ('tool_args', models.JSONField(blank=True, default=dict, verbose_name='工具参数')),
                ('tool_result', models.JSONField(blank=True, null=True, verbose_name='工具结果')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun', verbose_name='执行')),
            ],
            options={
                'verbose_name': 'Agent步骤',
                'verbose_name_plural': 'Agent步骤',
                'db_table': 'agent_steps',
                'ordering': ['order', 'id'],
            },
        ),
    ]
