# Generated by Django 6.0.5 on 2026-07-04 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("bids", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiAgentWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("bid_pipeline", "Bid pipeline")], db_index=True, default="bid_pipeline", max_length=32)),
                ("title", models.CharField(default="", max_length=256)),
                ("objective", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("done", "Done"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=16)),
                ("current_node_key", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("node_count", models.IntegerField(default=0)),
                ("completed_nodes", models.IntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("bid", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="multi_agent_workflows", to="bids.bid")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="multi_agent_workflows", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "multi_agent_workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowNodeRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=128)),
                ("node_type", models.CharField(choices=[("analysis", "Analysis"), ("planning", "Planning"), ("writing", "Writing"), ("review", "Review")], max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("done", "Done"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=16)),
                ("order", models.IntegerField(default=0)),
                ("depends_on", models.JSONField(blank=True, default=list)),
                ("input_artifacts", models.JSONField(blank=True, default=list)),
                ("output_artifacts", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_nodes", to="agents.agent")),
                ("agent_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_nodes", to="agents.agentrun")),
                ("chapter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workflow_nodes", to="bids.bidchapter")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="agents.multiagentworkflow")),
            ],
            options={
                "db_table": "workflow_node_runs",
                "ordering": ["order", "id"],
                "unique_together": {("workflow", "key")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64)),
                ("title", models.CharField(default="", max_length=128)),
                ("artifact_type", models.CharField(default="json", max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifacts", to="agents.workflownoderun")),
                ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="agents.multiagentworkflow")),
            ],
            options={
                "db_table": "workflow_artifacts",
                "ordering": ["created_at", "id"],
                "unique_together": {("workflow", "key")},
            },
        ),
    ]
