# Generated by Django 6.0.5 on 2026-07-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_multi_agent_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="allowed_tools",
            field=models.JSONField(blank=True, default=list, help_text="Whitelisted tool names. Leave empty to allow all registered tools.", verbose_name="Allowed tools"),
        ),
        migrations.AddField(
            model_name="agentrun",
            name="memory_ids",
            field=models.JSONField(blank=True, default=list, help_text="Selected memory record IDs attached to this run.", verbose_name="Memory ids"),
        ),
        migrations.CreateModel(
            name="AgentArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=128)),
                ("title", models.CharField(default="", max_length=128)),
                ("artifact_type", models.CharField(default="json", max_length=32)),
                ("source", models.CharField(default="system", max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="agents.agentrun")),
                ("step", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="artifacts", to="agents.agentstep")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_artifacts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_artifacts",
                "ordering": ["created_at", "id"],
                "unique_together": {("run", "key")},
            },
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("scope", models.CharField(choices=[("user", "User"), ("workspace", "Workspace"), ("run", "Run")], db_index=True, default="workspace", max_length=16)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("pinned", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="memory_records", to="agents.agentrun")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_memories", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_memories",
                "ordering": ["-pinned", "-last_used_at", "-updated_at", "-id"],
            },
        ),
    ]
