# Generated by Django 6.0.5 on 2026-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_workbench_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="file_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected uploaded file IDs attached to this run.",
                verbose_name="File ids",
            ),
        ),
    ]
