# Generated by Django 6.0.5 on 2026-07-04 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentrun_file_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agent run', 'verbose_name_plural': 'Agent runs'},
        ),
        migrations.AlterModelOptions(
            name='agentstep',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Agent step', 'verbose_name_plural': 'Agent steps'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='default_max_steps',
            field=models.IntegerField(default=8, verbose_name='Default max steps'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='skill',
            field=models.CharField(default='bid-writing/bid-chapter-writer', help_text='Skill path under hermes_skills without the .md suffix.', max_length=128, verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.CharField(max_length=64, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='Extra system prompt content appended after the skill body.'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='answer',
            field=models.TextField(blank=True, default='', verbose_name='Final answer'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='error',
            field=models.TextField(blank=True, default='', verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='max_steps',
            field=models.IntegerField(default=8, verbose_name='Max steps'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='session_id',
            field=models.CharField(blank=True, default='', help_text='Hermes session key used across the run.', max_length=64, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='step_count',
            field=models.IntegerField(default=0, verbose_name='Step count'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='task',
            field=models.TextField(verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='tools_used',
            field=models.JSONField(blank=True, default=list, verbose_name='Tools used'),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun', verbose_name='Run'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('skipped', 'Skipped')], default='ok', max_length=16),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='thought',
            field=models.TextField(blank=True, default='', verbose_name='Thought'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='tool_args',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tool args'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='tool_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Tool name'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='tool_result',
            field=models.JSONField(blank=True, null=True, verbose_name='Tool result'),
        ),
        migrations.AlterField(
            model_name='agentstep',
            name='type',
            field=models.CharField(choices=[('plan', 'Plan'), ('tool_call', 'Tool call'), ('tool_result', 'Tool result'), ('answer', 'Answer'), ('error', 'Error')], max_length=16, verbose_name='Type'),
        ),
    ]
