# Generated by Django 6.0.5 on 2026-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentrun_options_alter_agentstep_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='skill',
            field=models.CharField(default='agent-engineering/general-operator', help_text='Skill path under hermes_skills without the .md suffix.', max_length=128, verbose_name='Skill'),
        ),
    ]
