# Generated by Django 6.0.5 on 2026-07-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_chat_workbench_defaults'),
        ('projects', '0002_chat_workbench_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='projects.conversation', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='projects.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='source',
            field=models.CharField(db_index=True, default='manual', help_text='chat_turn | manual | workflow', max_length=32, verbose_name='Source'),
        ),
    ]
