# Generated by Django 6.0.5 on 2026-07-12 15:29

from django.db import migrations, models


def normalize_removed_workflow_sources(apps, schema_editor):
    agent_run = apps.get_model('agents', 'AgentRun')
    agent_run.objects.filter(source='workflow').update(source='manual')


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentrun_conversation_link'),
    ]

    operations = [
        migrations.RunPython(normalize_removed_workflow_sources, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='WorkflowArtifact',
        ),
        migrations.DeleteModel(
            name='WorkflowNodeRun',
        ),
        migrations.DeleteModel(
            name='MultiAgentWorkflow',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='celery_task_id',
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='source',
            field=models.CharField(db_index=True, default='manual', help_text='chat_turn | manual', max_length=32, verbose_name='Source'),
        ),
    ]
