# Generated by Django 6.0.5 on 2026-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_workflownoderun_workflow_and_more'),
        ('ai_config', '0005_delete_generationtask'),
        ('bids', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidStep',
        ),
        migrations.DeleteModel(
            name='BidChapter',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
