"""Persist generated markdown, docx, or xlsx content as a downloadable file."""

import csv
import io
import os
import re
import zipfile
from xml.sax.saxutils import escape

from django.conf import settings

from apps.files.models import UploadedFile
from apps.files.validation import detect_file_type

META = {
    "source": "builtin",
    "runtime": "full",
    "notes": "Stores generated files in the existing upload system.",
}

SCHEMA = {
    "name": "doc_export",
    "description": "Export generated content as Markdown, Word, or Excel and store it as a downloadable file.",
    "parameters": {
        "type": "object",
        "properties": {
            "content": {
                "type": "string",
                "description": "Markdown body to export. For Excel, this can be a markdown table or CSV text.",
            },
            "format": {
                "type": "string",
                "enum": ["docx", "markdown", "xlsx"],
                "description": "Target file format. Defaults to docx.",
            },
            "columns": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Optional Excel header row.",
            },
            "rows": {
                "type": "array",
                "items": {
                    "type": "array",
                    "items": {
                        "type": ["string", "number", "boolean", "null"],
                    },
                },
                "description": "Optional Excel rows. Use this when the user asks for a spreadsheet.",
            },
            "sheet_name": {
                "type": "string",
                "description": "Optional Excel sheet name.",
            },
            "title": {
                "type": "string",
                "description": "Document title used for the exported filename.",
            },
        },
    },
}


def _bytes_to_uploaded(*, user, filename, content_bytes):
    from django.core.files.base import ContentFile

    rel_dir = f"uploads/{user.id}"
    media_root = settings.MEDIA_ROOT or "media"
    os.makedirs(os.path.join(media_root, rel_dir), exist_ok=True)
    uploaded = UploadedFile.objects.create(
        user=user,
        original_name=filename,
        file_type=detect_file_type(filename),
        file_size=len(content_bytes),
        description="Generated by doc_export.",
    )
    uploaded.file.save(filename, ContentFile(content_bytes))
    uploaded.save()
    return uploaded


def handle(args, context=None):
    content = args.get("content") or ""

    fmt = args.get("format") or "docx"
    if fmt not in {"docx", "markdown", "xlsx"}:
        return {"ok": False, "error": f"Unsupported format: {fmt}"}
    if fmt != "xlsx" and not content:
        return {"ok": False, "error": "Missing content."}

    title = _safe_title(args.get("title") or "document")
    user = (context or {}).get("user")
    if user is None:
        return {"ok": False, "error": "Export requires an authenticated user context."}

    if fmt == "markdown":
        filename = f"{title}.md"
        payload = content.encode("utf-8")
    elif fmt == "xlsx":
        rows = _resolve_rows(args, content)
        if not rows:
            return {"ok": False, "error": "Excel export requires rows, columns, or table content."}
        filename = f"{title}.xlsx"
        payload = _build_xlsx(rows, sheet_name=args.get("sheet_name") or "Sheet1")
    else:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()
        doc.add_heading(title, level=0).alignment = WD_ALIGN_PARAGRAPH.CENTER
        for line in content.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("#"):
                level = min(stripped.count("#"), 3)
                doc.add_heading(stripped.strip("# "), level=level)
            elif stripped.startswith(("-", "*")):
                doc.add_paragraph(stripped.strip("-* "), style="List Bullet")
            else:
                doc.add_paragraph(stripped)

        import io

        buffer = io.BytesIO()
        doc.save(buffer)
        filename = f"{title}.docx"
        payload = buffer.getvalue()

    try:
        uploaded = _bytes_to_uploaded(user=user, filename=filename, content_bytes=payload)
    except Exception as exc:
        return {"ok": False, "error": f"Failed to save exported file: {exc}"}

    return {
        "ok": True,
        "result": {
            "file_id": uploaded.id,
            "filename": filename,
            "format": fmt,
            "url": uploaded.file.url,
            "preview": content[:200] if content else _preview_rows(rows if fmt == "xlsx" else []),
        },
    }


def _safe_title(value):
    title = str(value or "document").strip() or "document"
    title = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "_", title)
    return title[:80].strip(" ._") or "document"


def _resolve_rows(args, content):
    columns = args.get("columns") or []
    rows = args.get("rows") or []

    if rows:
        normalized = _normalize_rows(rows)
        if columns:
            return [list(columns), *normalized]
        return normalized

    if columns:
        return [list(columns)]

    return _rows_from_content(content)


def _normalize_rows(rows):
    if not isinstance(rows, list):
        return []

    normalized = []
    dict_keys = []
    if rows and all(isinstance(row, dict) for row in rows):
        for row in rows:
            for key in row:
                if key not in dict_keys:
                    dict_keys.append(key)
        normalized.append(dict_keys)
        for row in rows:
            normalized.append([row.get(key, "") for key in dict_keys])
        return normalized

    for row in rows:
        if isinstance(row, (list, tuple)):
            normalized.append(list(row))
        else:
            normalized.append([row])
    return normalized


def _rows_from_content(content):
    text = (content or "").strip()
    if not text:
        return []

    markdown_rows = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or "|" not in stripped:
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if cells and all(re.fullmatch(r":?-{3,}:?", cell or "") for cell in cells):
            continue
        markdown_rows.append(cells)
    if markdown_rows:
        return markdown_rows

    try:
        csv_rows = [row for row in csv.reader(io.StringIO(text)) if row]
        if len(csv_rows) > 1 or (csv_rows and len(csv_rows[0]) > 1):
            return csv_rows
    except csv.Error:
        pass

    return [[line.strip()] for line in text.splitlines() if line.strip()]


def _build_xlsx(rows, sheet_name="Sheet1"):
    normalized_rows = _normalize_rows(rows)
    sheet = _safe_sheet_name(sheet_name)
    files = {
        "[Content_Types].xml": _content_types_xml(),
        "_rels/.rels": _root_rels_xml(),
        "xl/workbook.xml": _workbook_xml(sheet),
        "xl/_rels/workbook.xml.rels": _workbook_rels_xml(),
        "xl/styles.xml": _styles_xml(),
        "xl/worksheets/sheet1.xml": _worksheet_xml(normalized_rows),
    }

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path, body in files.items():
            archive.writestr(path, body.encode("utf-8"))
    return buffer.getvalue()


def _safe_sheet_name(value):
    name = re.sub(r"[\[\]:*?/\\]+", " ", str(value or "Sheet1")).strip() or "Sheet1"
    return name[:31]


def _worksheet_xml(rows):
    row_xml = []
    for row_index, row in enumerate(rows, start=1):
        cells = []
        for column_index, value in enumerate(row, start=1):
            ref = f"{_column_name(column_index)}{row_index}"
            cells.append(_cell_xml(ref, value))
        row_xml.append(f'<row r="{row_index}">{"".join(cells)}</row>')
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheetData>'
        f'{"".join(row_xml)}'
        '</sheetData>'
        '</worksheet>'
    )


def _cell_xml(ref, value):
    if value is None:
        return f'<c r="{ref}"/>'
    if isinstance(value, bool):
        return f'<c r="{ref}" t="b"><v>{1 if value else 0}</v></c>'
    if isinstance(value, (int, float)):
        return f'<c r="{ref}"><v>{value}</v></c>'

    text = str(value)
    number = _parse_number(text)
    if number is not None:
        return f'<c r="{ref}"><v>{number}</v></c>'
    return f'<c r="{ref}" t="inlineStr"><is><t>{escape(text)}</t></is></c>'


def _parse_number(text):
    cleaned = text.strip().replace(",", "")
    if not cleaned or cleaned.endswith("%"):
        return None
    try:
        return int(cleaned) if re.fullmatch(r"[+-]?\d+", cleaned) else float(cleaned)
    except ValueError:
        return None


def _column_name(index):
    name = ""
    while index:
        index, remainder = divmod(index - 1, 26)
        name = chr(65 + remainder) + name
    return name


def _content_types_xml():
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
        '</Types>'
    )


def _root_rels_xml():
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
        '</Relationships>'
    )


def _workbook_xml(sheet_name):
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        '<sheets>'
        f'<sheet name="{escape(sheet_name)}" sheetId="1" r:id="rId1"/>'
        '</sheets>'
        '</workbook>'
    )


def _workbook_rels_xml():
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
        '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
        '</Relationships>'
    )


def _styles_xml():
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        '<fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts>'
        '<fills count="1"><fill><patternFill patternType="none"/></fill></fills>'
        '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>'
        '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
        '<cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs>'
        '</styleSheet>'
    )


def _preview_rows(rows):
    return "\n".join(", ".join(str(cell) for cell in row) for row in rows[:3])[:200]
